AWSTemplateFormatVersion: 2010-09-09
Description: Deploys an EKS cluster into an existing VPC.
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into an existing VPC
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic configuration
        Parameters:
          - RemoteAccessCIDR
          - KeyPairName
          - ConfigSetName
      - Label:
          default: Network configuration
        Parameters:
          - VPCID
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - PrivateSubnet3ID
          - PublicSubnet1ID
          - PublicSubnet2ID
          - PublicSubnet3ID
          - HttpProxy
      - Label:
          default: Bastion host configuration
        Parameters:
          - ProvisionBastionHost
          - OnDemandBastionPercentage
      - Label:
          default: Amazon EKS configuration
        Parameters:
          - EKSClusterName
          - KubernetesVersion
          - EKSPublicAccessEndpoint
          - AdditionalEKSAdminUserArn
          - AdditionalEKSAdminRoleArn
          - RoleArn
      - Label:
          default: Default EKS node group configuration
        Parameters:
          - NodeInstanceType
          - NumberOfNodes
          - MaxNumberOfNodes
          - NodeInstanceFamily
          - NodeGroupType
          - OnDemandPercentage
          - NodeGroupOS
      - Label:
          default: Calico policy (APN security partner)
        Parameters:
          - CalicoIntegration
      - Label:
          default: Kubernetes add-ins
        Parameters:
          - LoadBalancerController
          - CertManager
          - ClusterAutoScaler
          - MetricsServer
          - EfsStorageClass
    ParameterLabels:
      KeyPairName:
        default: SSH key name
      RemoteAccessCIDR:
        default: Allowed external access CIDR
      NodeInstanceType:
        default: Instance type
      NumberOfNodes:
        default: Number of nodes
      PublicSubnet1ID:
        default: Public subnet 1 ID
      PublicSubnet2ID:
        default: Public subnet 2 ID
      PublicSubnet3ID:
        default: Public subnet 3 ID
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      PrivateSubnet3ID:
        default: Private subnet 3 ID
      VPCID:
        default: VPC ID
      RoleArn:
        defale: Role ARN
      AdditionalEKSAdminUserArn:
        default: Additional EKS admin ARN (IAM user)
      AdditionalEKSAdminRoleArn:
        default: Additional EKS admin ARN (IAM role)
      ClusterAutoScaler:
        default: Cluster autoscaler
      MetricsServer:
        default: Metrics server
      EfsStorageClass:
        default: EFS storage class
      ProvisionBastionHost:
        default: Provision bastion host
      OnDemandBastionPercentage:
        default: Bastion host on-demand percentage
      LoadBalancerController:
        default: AWS load balancer controller
      CertManager:
        default: Certificate manager
      EKSClusterName:
        default: EKS cluster name
      KubernetesVersion:
        default: Kubernetes version
      CalicoIntegration:
        default: Calico policy integration
      EKSPublicAccessEndpoint:
        default: EKS public access endpoint
      HttpProxy:
        default: HTTP proxy
      ConfigSetName:
        default: Config set name
      MaxNumberOfNodes:
        default: Maximum number of nodes
      NodeInstanceFamily:
        default: Instance family
      NodeGroupType:
        default: Node group type
      OnDemandPercentage:
        default: EKS node on-demand percentage
      NodeGroupOS:
        default: Node group operating system
      OrgID:
        default: Organization ID of your Anypoint
Parameters:
  # NOTE: Don't change the type of KeyPairName parameter back to AWS::EC2::KeyPair::KeyName.
  # String type is intentional as it enables default (empty) value. By using defaults, we
  # promote AWS Systems Manager Session Manager service, which is a recommended way
  # to connect to EC2 instances.
  KeyPairName:
    Type: String
    Description: >-
      Name of an existing key pair, which allows you to securely connect to
      your instance after it launches. Leave empty to proceed without a key
      pair. You would need to use AWS Systems Manager Session Manager to
      connect to the provisioned EC2 instances.
    Default: 'testKeyPair'
  RemoteAccessCIDR:
    Type: String
    Description: >-
      Trusted IPv4 CIDR block or VPC prefix list that is permitted remote
      access to your instances if desired in addition to
      AWS Systems Manager (SSM) access.
    Default: ''
  EKSPublicAccessEndpoint:
    Type: String
    Description: >-
      Configure access to the Kubernetes API server endpoint from outside of
      your VPC.
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
  RoleArn:
    Type: String
    Description: Role Arn of EKS Cluster
    AllowedPattern: ^arn:(aws|aws-cn|aws-us-gov):iam::[0-9]{12}:.*|^$
    Default: ''
  AdditionalEKSAdminUserArn:
    Type: String
    Description: >-
      (Optional) IAM user Amazon Resource Name (ARN) to be granted
      administrative access to the EKS cluster.
    AllowedPattern: ^arn:(aws|aws-cn|aws-us-gov):iam::[0-9]{12}:.*|^$
    Default: ''
  AdditionalEKSAdminRoleArn:
    Type: String
    Description: >-
      (Optional) IAM role Amazon Resource Name (ARN) to be granted
      administrative access to the EKS cluster.
    AllowedPattern: ^arn:(aws|aws-cn|aws-us-gov):iam::[0-9]{12}:.*|^$
    Default: ''
  NodeInstanceType:
    Type: String
    Description: EC2 instance type.
    ConstraintDescription: Must be a valid EC2 instance type.
    Default: t3.medium
  NumberOfNodes:
    Type: Number
    Description: >-
      Number of Amazon EKS node instances. The default is one for each of the
      three Availability Zones.
    MinValue: 0
    MaxValue: 3
    Default: 3
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: ID of your existing VPC (e.g., vpc-0343606e).
  PublicSubnet1ID:
    Type: String
    Description: >-
      ID of the public subnet in Availability Zone 1 of your existing VPC
      (example: subnet-a0246dcd).
    Default: ''
  PublicSubnet2ID:
    Type: String
    Description: >-
      ID of the public subnet in Availability Zone 2 of your existing VPC
      (example: subnet-b1236eea).
    Default: ''
  PublicSubnet3ID:
    Type: String
    Description: >-
      ID of the public subnet in Availability Zone 3 of your existing VPC
      (example: subnet-c3456aba).
    Default: ''
  PrivateSubnet1ID:
    Type: AWS::EC2::Subnet::Id
    Description: >-
      ID of the private subnet in Availability Zone 1 of your existing VPC
      (example: subnet-fe9a8b32).
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
    Description: >-
      ID of the private subnet in Availability Zone 2 of your existing VPC
      (example: subnet-be8b01ea).
  PrivateSubnet3ID:
    Type: AWS::EC2::Subnet::Id
    Description: >-
      ID of the private subnet in Availability Zone 3 of your existing VPC
      (example: subnet-abd39039).
    Default: ''
  ClusterAutoScaler:
    Type: String
    Description: Choose "Enabled" to enable Kubernetes cluster autoscaler.
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
  MetricsServer:
    Type: String
    Description: >-
      Choose "Enabled" to enable Kubernetes metrics server. Use cases include
      CPU/Memory based horizontal auto-scaling
      (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
      and automatically adjusting/suggesting resources needed by containers
      (https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/).
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
  EfsStorageClass:
    Type: String
    Description: Choose "Enabled" to enable EFS storage class.
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
  HttpProxy:
    Type: String
    Description: >-
      (Optional) HTTP(S) proxy configuration. If provided, all worker nodes and
      pod egress traffic uses this proxy. Example: http://10.101.0.100:3128/.
    Default: ''
  ProvisionBastionHost:
    Type: String
    Description: Choose "Disabled" to skip creating a bastion host.
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
  OnDemandBastionPercentage:
    Type: Number
    Description: >-
      Set the percentage of on-demand instances and spot instances. With a
      default of 100, the percentages are 100% for on-demand instances and 0%
      for spot instances.
    MinValue: 0
    MaxValue: 100
    Default: 100
  LoadBalancerController:
    Type: String
    Description: >-
      Choose "Disabled" to skip deploying the AWS load balancer controller.
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
  CertManager:
    Type: String
    Description: >-
      Choose "Disabled" to skip deploying the certificate manager.
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
  EKSClusterName:
    Type: String
    Description: >-
      (Optional) Name for the EKS cluster. If left blank, one is
      auto-generated. This must be unique within the Region.
    Default: 'TestEKSCluster'
  KubernetesVersion:
  # https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar
    Type: String
    Description: >-
      (Optional) Kubernetes control plane version. If ConfigSetName is set,
      this value will be ignored and the Kubernetes version specified in the
      advanced configuration template (including the default) will be used.
    AllowedValues: [1.26,1.25,1.24, 1.23, 1.22]
    Default: 1.25
  ConfigSetName:
    Type: String
    Description: >-
      (Optional) Name used to map advanced parameters to an EKS cluster. If you
      launched an advanced configuration stack and would like to apply it's
      values to this cluster, this name must match the "Config set name"
      parameter in that stack. If left blank, a new config set is created using
      default values.
    Default: ''
  CalicoIntegration:
    Type: String
    Description: For more information see https://www.projectcalico.org/.
    AllowedValues: [Enabled, Disabled]
    Default: Disabled
  MaxNumberOfNodes:
    Type: Number
    Description: >-
      Maximum number of Amazon EKS node instances. The default is three.
    MinValue: 0
    MaxValue: 3
    Default: 3
  NodeInstanceFamily:
    Type: String
    Description: >-
      Choose the instance family to match the value of "Node instance type".
    AllowedValues: [Standard, ARM, GPU]
    Default: Standard
  NodeGroupType:
    Type: String
    Description: >-
      Choose "Unmanaged" to create an Auto Scaling group without using the
      EKS-managed node groups feature.
    AllowedValues: [Managed, Unmanaged]
    Default: Unmanaged
  OnDemandPercentage:
    Type: Number
    Description: >-
      (Optional) Only applies if the NodeGroupType parameter is set to
      "Unmanaged". Set the percentage of on-demand instances and spot
      instances. With a default of 100, the percentages are 100% for on-demand
      instances and 0% for spot instances. Additionally, if ConfigSetName is
      set, this value will be ignored. The on-demand percentage value specified
      in the advanced configuration template (including the default) will be
      used.
    MinValue: 0
    MaxValue: 100
    Default: 100
  NodeGroupOS:
    Type: String
    Description: >-
      Operating system to use for node instances. Note that if you choose
      "Windows", an additional Amazon Linux node group is created.
    AllowedValues: [Amazon Linux 2, Bottlerocket, Windows]
    Default: Amazon Linux 2
Resources:
  EKSStack:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Parameters:
        # Basic configuration
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        KeyPairName: !Ref KeyPairName
        # Network configuration
        VPCID: !Ref VPCID
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        PrivateSubnet3ID: !Ref PrivateSubnet3ID
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        PublicSubnet3ID: !Ref PublicSubnet3ID
        HttpProxy: !Ref HttpProxy
        # Bastion host configuration
        ProvisionBastionHost: !Ref ProvisionBastionHost
        # Amazon EKS configuration
        RoleArn: !Ref RoleArn
        EKSClusterName: !Ref EKSClusterName
        EKSPublicAccessEndpoint: !Ref EKSPublicAccessEndpoint
        AdditionalEKSAdminUserArn: !Ref AdditionalEKSAdminUserArn
        AdditionalEKSAdminRoleArn: !Ref AdditionalEKSAdminRoleArn
        # Default EKS node group configuration
        NodeInstanceType: !Ref NodeInstanceType
        NumberOfNodes: !Ref NumberOfNodes
        MaxNumberOfNodes: !Ref MaxNumberOfNodes
        NodeInstanceFamily: !Ref NodeInstanceFamily
        NodeGroupType: !Ref NodeGroupType
        NodeGroupOS: !Ref NodeGroupOS
        # Calico policy (APN security partner)
        CalicoIntegration: !Ref CalicoIntegration
        # Kubernetes add-ins
        ProvisionLoadBalancerController: !Ref LoadBalancerController
        ProvisionCertManager: !Ref CertManager
        ProvisionClusterAutoScaler: !Ref ClusterAutoScaler
        ProvisionMetricsServer: !Ref MetricsServer
        EfsStorageClass: !Ref EfsStorageClass
Outputs:
  KubernetesVersion:
    Value: !Ref KubernetesVersion
  EKSClusterName:
    Value: !Ref EKSClusterName
